Add description of new syntax
knowsys/nemo-doc pull request #13
Opened 2024-12-11 13:41 UTC by aannleax

Adds description for format strings and attributes. Corrects the statement that single-quoted or multiline strings are supported

2024-12-11 14:19 UTC, matzemathics approved these changes

2024-12-12 13:38 UTC, mmarx requested changes
Found a typo, looks good otherwise

2024-12-12 13:38 UTC, mmarx commented on src/content/docs/reference/attributes.md
> +#[atribute_name(parameter_1, parameter_2, ...)]
`attribute_name`

2025-01-14 15:46 UTC, mmarx approved these changes

2025-01-14 15:46 UTC, merged